@startuml

' In a Jack program, exactly one class must be named [Main],
' and it must contain a method called [main].

class Main

class GameManager {
    GameManager()
    +feed(string input)
    -TetrisBase curBlock
    -wait()
    -check()
    -generateBlock()
    -string curState
}

class Row {
    +Array row
}

class GameBoard {
    +update(TetrisBase)
    -Array<Row> line
    -draw()
}

class TetrisBase {
    +tryRotate(bool left = true) -> bool
    +tryMoveDown() -> bool
    -int row
    -int col
    -moveDown()
    -roate(bool left = true)
    -draw()
}

class TetrisI
class TetrisJ
class TetrisL
class TetrisO
class TetrisS
class TetrisT
class TetrisZ

TetrisBase <|-- TetrisI
TetrisBase <|-- TetrisJ
TetrisBase <|-- TetrisL
TetrisBase <|-- TetrisO
TetrisBase <|-- TetrisS
TetrisBase <|-- TetrisT
TetrisBase <|-- TetrisZ

Main *-- GameManager
GameManager *-- GameBoard
GameManager *-- TetrisBase

@enduml